import json, pathlib

cells_data = [
    ("markdown", "md-01", "# 02 - PostGIS Analysis\n**Projekt:** Erreichbarkeit von Apotheken\n\n1. Geodaten in PostGIS laden\n2. ST_Within: Apotheken pro Gemeinde\n3. ST_DWithin: Radius-Analyse\n4. ST_Distance: Minimaldistanz\n5. Bevoelkerungsanalyse"),
    ("code", "c1", "import geopandas as gpd\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom pathlib import Path\nfrom sqlalchemy import create_engine, text\nimport warnings\nwarnings.filterwarnings('ignore')\n\nPROCESSED = Path('../data/processed')\nOUTPUTS = Path('../outputs/maps')\nOUTPUTS.mkdir(parents=True, exist_ok=True)\n\nDB_URL = 'postgresql://postgres:postgres@localhost:5432/pharmacy_ch'\nengine = create_engine(DB_URL)\n\nwith engine.connect() as conn:\n    r = conn.execute(text('SELECT PostGIS_Full_Version()'))\n    print('PostGIS:', r.fetchone()[0][:60])\nprint('Verbindung OK')"),
    ("markdown", "md-02", "## 1. Geodaten in PostGIS laden\n`to_postgis()` schreibt GeoDataFrame direkt in PostgreSQL.\nSpatial Index (GIST) beschleunigt raeumliche Abfragen um Faktor 100+."),
    ("code", "c2", "gdf_pharmacies = gpd.read_file(PROCESSED / 'pharmacies_ch.geojson')\ngdf_gemeinden  = gpd.read_file(PROCESSED / 'gemeinden_ch.geojson')\ngdf_plz        = gpd.read_file(PROCESSED / 'plz_ch.geojson')\nprint('Apotheken:', len(gdf_pharmacies))\nprint('Gemeinden:', len(gdf_gemeinden))\nprint('PLZ:      ', len(gdf_plz))"),
    ("code", "c3", "print('Schreibe in PostGIS...')\ngdf_pharmacies.to_postgis('pharmacies', engine, if_exists='replace', index=False)\ngdf_gemeinden.to_postgis('gemeinden',   engine, if_exists='replace', index=False)\ngdf_plz.to_postgis('plz',               engine, if_exists='replace', index=False)\n\nwith engine.connect() as conn:\n    conn.execute(text('CREATE INDEX IF NOT EXISTS idx_pharm_geom ON pharmacies USING GIST(geometry)'))\n    conn.execute(text('CREATE INDEX IF NOT EXISTS idx_gem_geom   ON gemeinden  USING GIST(geometry)'))\n    conn.execute(text('CREATE INDEX IF NOT EXISTS idx_plz_geom   ON plz        USING GIST(geometry)'))\n    conn.commit()\nprint('Alle Tabellen + Spatial Indexes erstellt!')"),
    ("markdown", "md-03", "## 2. ST_Within: Apotheken pro Gemeinde\n`ST_Within(punkt, polygon)` = True wenn Punkt innerhalb Polygon liegt.\nGrundlegender raeumlicher Join fuer unsere Analyse."),
    ("code", "c4", "query = '''\nSELECT\n    g.bfs_nummer,\n    g.name AS gemeinde,\n    g.einwohnerzahl,\n    COUNT(p.osm_id) AS apotheken_anzahl\nFROM gemeinden g\nLEFT JOIN pharmacies p ON ST_Within(p.geometry, g.geometry)\nGROUP BY g.bfs_nummer, g.name, g.einwohnerzahl\nORDER BY apotheken_anzahl DESC\n'''\ndf_apo = pd.read_sql(query, engine)\nprint('Gemeinden total:         ', len(df_apo))\nprint('Ohne Apotheke:           ', (df_apo['apotheken_anzahl']==0).sum())\nprint('Mit Apotheke:            ', (df_apo['apotheken_anzahl']>0).sum())\nprint()\ndf_apo.head(10)"),
    ("markdown", "md-04", "## 3. ST_Distance: Minimaldistanz zur naechsten Apotheke\nKernabfrage: Fuer jede Gemeinde die Distanz zur naechsten Apotheke.\nIn LV95 (EPSG:2056) ist die Einheit Meter."),
    ("code", "c5", "query = '''\nSELECT\n    g.bfs_nummer,\n    g.name AS gemeinde,\n    g.einwohnerzahl,\n    g.kantonsnummer,\n    MIN(ST_Distance(ST_Centroid(g.geometry), p.geometry)) AS min_distanz_m\nFROM gemeinden g\nCROSS JOIN pharmacies p\nGROUP BY g.bfs_nummer, g.name, g.einwohnerzahl, g.kantonsnummer\nORDER BY min_distanz_m DESC\n'''\ndf_dist = pd.read_sql(query, engine)\nprint('Abfrage erfolgreich:', len(df_dist), 'Gemeinden')\nprint()\nprint('Schlechtestversorgte Gemeinden:')\ndf_dist.head(10)"),
    ("code", "c6", "df_dist['versorgung'] = pd.cut(\n    df_dist['min_distanz_m'],\n    bins=[0, 1000, 5000, 10000, float('inf')],\n    labels=['< 1km', '1-5km', '5-10km', '> 10km']\n)\nprint('Versorgungskategorien:')\nprint(df_dist['versorgung'].value_counts().sort_index())\nprint()\ntotal = df_dist['einwohnerzahl'].sum()\nfor label in ['< 1km','1-5km','5-10km','> 10km']:\n    bev = df_dist[df_dist['versorgung']==label]['einwohnerzahl'].sum()\n    pct = bev/total*100\n    print(f'{label}: {bev:>9,.0f} Personen ({pct:.1f}%)')"),
    ("code", "c7", "gdf_merged = gdf_gemeinden.merge(df_dist[['bfs_nummer','min_distanz_m','versorgung']], on='bfs_nummer', how='left')\n\nfig, ax = plt.subplots(figsize=(14, 10))\ngdf_merged.plot(\n    column='min_distanz_m', ax=ax, cmap='RdYlGn_r',\n    legend=True,\n    legend_kwds={'label':'Distanz zur naechsten Apotheke (m)','shrink':0.6},\n    missing_kwds={'color':'lightgrey'}\n)\ngdf_pharmacies.plot(ax=ax, color='blue', markersize=2, alpha=0.5, label='Apotheke')\nax.set_title('Distanz zur naechsten Apotheke pro Gemeinde', fontsize=14, fontweight='bold')\nax.set_axis_off()\nplt.tight_layout()\nout = Path('../outputs/maps/02_distanz_apotheke.png')\nplt.savefig(out, dpi=150, bbox_inches='tight')\nplt.show()\nprint('Karte gespeichert:', out)"),
    ("code", "c8", "unterversorgt_5km  = df_dist[df_dist['min_distanz_m'] > 5000]\nunterversorgt_10km = df_dist[df_dist['min_distanz_m'] > 10000]\ntotal_bev = gdf_gemeinden['einwohnerzahl'].sum()\n\nprint('=== BEVOELKERUNGSANALYSE ===')\nprint(f'Gesamtbevoelkerung CH:        {total_bev:>10,.0f}')\nprint()\nprint(f'Personen > 5km von Apotheke:  {unterversorgt_5km[\"einwohnerzahl\"].sum():>10,.0f} ({unterversorgt_5km[\"einwohnerzahl\"].sum()/total_bev*100:.1f}%)')\nprint(f'Personen > 10km von Apotheke: {unterversorgt_10km[\"einwohnerzahl\"].sum():>10,.0f} ({unterversorgt_10km[\"einwohnerzahl\"].sum()/total_bev*100:.1f}%)')\nprint()\nprint(f'Gemeinden > 5km:  {len(unterversorgt_5km)}')\nprint(f'Gemeinden > 10km: {len(unterversorgt_10km)}')"),
    ("code", "c9", "df_dist.to_csv('../data/processed/gemeinden_distanz_apotheke.csv', index=False)\ngdf_merged.to_file('../data/processed/gemeinden_mit_distanz.geojson', driver='GeoJSON')\nprint('Gespeichert:')\nprint('  data/processed/gemeinden_distanz_apotheke.csv')\nprint('  data/processed/gemeinden_mit_distanz.geojson')\nprint('Weiter mit: 03_isochrones_ors.ipynb')")
]

nb = {'cells':[],'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':'3.13.0'}},'nbformat':4,'nbformat_minor':5}
for ctype,cid,src in cells_data:
    cell = {'cell_type':ctype,'id':cid,'metadata':{},'source':src}
    if ctype=='code':
        cell['execution_count']=None
        cell['outputs']=[]
    nb['cells'].append(cell)

path = pathlib.Path(r'C:\Projects\pharmacy-accessibility-ch\notebooks\02_postgis_analysis.ipynb')
with open(path,'w',encoding='utf-8') as f:
    json.dump(nb,f,indent=1,ensure_ascii=False)
print('Notebook 02 geschrieben!')